### ISSUE TITLE
Error on Synology Docker

### ISSUE THREAD

**Issue by Krocko** [MiguelRipoll23/homebridge-securitysystem#12]
Hello. I got the following error.
Is there something you can do to fix this?
```
(node:790) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge/.node-persist'
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:790) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[9/27/2019, 8:30:01 PM] [Homebase NAS] current power state is: true
```

```
[9/27/2019, 8:30:42 PM] [Security system] Target state (Night)
(node:790) UnhandledPromiseRejectionWarning: TypeError: storage.setItem is not a function
    at SecuritySystem.save (/homebridge/node_modules/homebridge-securitysystem/index.js:151:17)
    at SecuritySystem.setTargetState (/homebridge/node_modules/homebridge-securitysystem/index.js:274:10)
    at Characteristic.SecuritySystemTargetState.emit (events.js:198:13)
    at Characteristic.SecuritySystemTargetState.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[9/27/2019, 8:30:45 PM] [Security system] Current state (Night)
(node:790) UnhandledPromiseRejectionWarning: TypeError: storage.setItem is not a function
    at SecuritySystem.save (/homebridge/node_modules/homebridge-securitysystem/index.js:151:17)
    at SecuritySystem.updateCurrentState (/homebridge/node_modules/homebridge-securitysystem/index.js:181:10)
    at SecuritySystem.<anonymous> (/homebridge/node_modules/homebridge-securitysystem/index.js:305:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[9/27/2019, 8:31:06 PM] [Security system] Trigger timeout (Started)
(node:790) UnhandledPromiseRejectionWarning: TypeError: storage.setItem is not a function
    at SecuritySystem.save (/homebridge/node_modules/homebridge-securitysystem/index.js:151:17)
    at SecuritySystem.setSwitchState (/homebridge/node_modules/homebridge-securitysystem/index.js:318:10)
    at Characteristic.On.emit (events.js:198:13)
    at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[9/27/2019, 8:31:11 PM] [Security system] Current state (Alarm triggered)
(node:790) UnhandledPromiseRejectionWarning: TypeError: storage.setItem is not a function
    at SecuritySystem.save (/homebridge/node_modules/homebridge-securitysystem/index.js:151:17)
    at SecuritySystem.updateCurrentState (/homebridge/node_modules/homebridge-securitysystem/index.js:181:10)
    at SecuritySystem.<anonymous> (/homebridge/node_modules/homebridge-securitysystem/index.js:338:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[9/27/2019, 8:31:24 PM] [Security system] Target state (Night)
(node:790) UnhandledPromiseRejectionWarning: TypeError: storage.setItem is not a function
    at SecuritySystem.save (/homebridge/node_modules/homebridge-securitysystem/index.js:151:17)
    at SecuritySystem.setSwitchState (/homebridge/node_modules/homebridge-securitysystem/index.js:318:10)
    at Characteristic.On.emit (events.js:198:13)
    at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:790) UnhandledPromiseRejectionWarning: TypeError: storage.setItem is not a function
    at SecuritySystem.save (/homebridge/node_modules/homebridge-securitysystem/index.js:151:17)
    at SecuritySystem.setTargetState (/homebridge/node_modules/homebridge-securitysystem/index.js:274:10)
    at Characteristic.SecuritySystemTargetState.emit (events.js:198:13)
    at Characteristic.SecuritySystemTargetState.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Service.SecuritySystem.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:183:32)
    at SecuritySystem.setSwitchState (/homebridge/node_modules/homebridge-securitysystem/index.js:348:22)
    at Characteristic.On.emit (events.js:198:13)
    at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
[9/27/2019, 8:31:24 PM] [Security system] Current state (Night)
(node:790) UnhandledPromiseRejectionWarning: TypeError: storage.setItem is not a function
    at SecuritySystem.save (/homebridge/node_modules/homebridge-securitysystem/index.js:151:17)
    at SecuritySystem.updateCurrentState (/homebridge/node_modules/homebridge-securitysystem/index.js:181:10)
    at SecuritySystem.<anonymous> (/homebridge/node_modules/homebridge-securitysystem/index.js:305:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
[9/27/2019, 8:32:41 PM] [Security system] Target state (Home)
(node:790) UnhandledPromiseRejectionWarning: TypeError: storage.setItem is not a function
    at SecuritySystem.save (/homebridge/node_modules/homebridge-securitysystem/index.js:151:17)
    at SecuritySystem.setTargetState (/homebridge/node_modules/homebridge-securitysystem/index.js:274:10)
    at Characteristic.SecuritySystemTargetState.emit (events.js:198:13)
    at Characteristic.SecuritySystemTargetState.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
[9/27/2019, 8:32:44 PM] [Security system] Current state (Home)
(node:790) UnhandledPromiseRejectionWarning: TypeError: storage.setItem is not a function
    at SecuritySystem.save (/homebridge/node_modules/homebridge-securitysystem/index.js:151:17)
    at SecuritySystem.updateCurrentState (/homebridge/node_modules/homebridge-securitysystem/index.js:181:10)
    at SecuritySystem.<anonymous> (/homebridge/node_modules/homebridge-securitysystem/index.js:305:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
```

**Comment by MiguelRipoll23** [comment]
Seems like a bug, install the previous version using npm install `homebridge-securitysystem@1.4.4`. This will get fixed ASAP.

**Comment by Krocko** [comment]
Thanks for your fast response. 
Will do.

**Comment by MiguelRipoll23** [comment]
The issue you are seeing is appearing because you are using the `save_state` option but the plugin can't write the current state to the file system due to missing permissions. I just published a new version that may solve this issue just by changing the data directory path to the one Homebridge uses.

Hopefully it's fixed now.

**Comment by Krocko** [comment]
I installed v.1.5.2 and it is working without problems.
