### ISSUE TITLE
Security System Automatically Deactivating

### ISSUE THREAD

**Issue by page-squared** [MiguelRipoll23/homebridge-securitysystem#138]
### Plugin version

5.1.1

### Homebridge version

1.3.4

### What happened?

When the security system is set, it works well. But it automatically turns off after a certain number of minutes. I know I have a setting wrong, but I can't figure out where.

### Relevant log output

```shell
"name": "Security System",
    "default_mode": "Off",
    "arm_seconds": 0,
    "trigger_seconds": 0,
    "reset_minutes": 0,
    "audio": true,
    "audio_language": "en-US",
    "save_state": false,
    "proxy_mode": false,
    "test_mode": false,
    "home_arm_seconds": 0,
    "night_arm_seconds": 0,
    "away_arm_seconds": 60,
    "home_trigger_seconds": 0,
    "night_trigger_seconds": 0,
    "away_trigger_seconds": 60,
    "override_off": false,
    "reset_off_flow": true,
    "double_knock": false,
    "double_knock_seconds": 90,
    "double_knock_modes": [
        "Away"
    ],
    "tripped_sensor": false,
    "tripped_sensor_seconds": 5,
    "siren_sensor": true,
    "siren_sensor_seconds": 5,
    "reset_sensor": false,
    "mode_switches": false,
    "mode_off_switch": false,
    "mode_away_extended_switch": false,
    "mode_pause_switch": false,
    "pause_minutes": 0,
    "arming_lock_switch": false,
    "siren_switch": false,
    "siren_mode_switches": false,
    "audio_volume": "100",
    "audio_arming_looped": true,
    "audio_alert_looped": true,
    "accessory": "security-system"
```

**Comment by MiguelRipoll23** [comment]
Hey there,

I can't reproduce, could you please share the log?
Maybe you have an automation setting the security system's mode to Off.

**Comment by MiguelRipoll23** [comment]
The setting `reset_minutes` should be 1 at least, otherwise the security system mode will immediately return to the armed mode without triggering I think that's your issue.

I'll implement some validation there to block invalid values.

**Comment by page-squared** [comment]
I changed reset_minutes to 1 and it turned off after 1 minute so I changed it to 3 and it turned off after 1 minute.  I see the logs when it turns on, but not when it turns off.  The logs say I need to pair with homebridge, but it is paired.  I just unpaired it and repaired it and the same thing happened. Turned off after a minute (or even that long?).

[6/30/2021, 12:30:39 PM] ---
[6/30/2021, 12:30:39 PM] Loaded plugin: homebridge-config-ui-x@4.41.1
[6/30/2021, 12:30:39 PM] Registering platform 'homebridge-config-ui-x.config'
[6/30/2021, 12:30:39 PM] ---
[6/30/2021, 12:30:39 PM] Loading 1 platforms...
[6/30/2021, 12:30:39 PM] [Config] Initializing config platform...
[6/30/2021, 12:30:39 PM] [Config] Running in Service Mode
[6/30/2021, 12:30:39 PM] Loading 1 accessories...
[6/30/2021, 12:30:39 PM] [Security System] Initializing security-system accessory...
[6/30/2021, 12:30:39 PM] [Security System] Default mode (Off)
[6/30/2021, 12:30:39 PM] [Security System] Arm delay (0 second/s)
[6/30/2021, 12:30:39 PM] [Security System] Trigger delay (0 second/s)
[6/30/2021, 12:30:39 PM] [Security System] Audio (Enabled)
Preparing Advertiser for 'Homebridge E48B A492' using bonjour-hap backend!
Setup Payload:
X-HM://0023ISYWYLJEL
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge E48B A492' using bonjour-hap backend!
[6/30/2021, 12:30:39 PM] Homebridge v1.3.4 (Homebridge E48B) is running on port 52347.
[6/30/2021, 12:30:45 PM] [Security System] Target mode (Home)
[6/30/2021, 12:30:45 PM] [Security System] Current mode (Home)
[6/30/2021, 12:30:46 PM] Error: spawn ffplay ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[6/30/2021, 12:30:46 PM] Got SIGTERM, shutting down Homebridge...
[6/30/2021, 12:30:51 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[6/30/2021, 12:30:56 PM] [HB Supervisor] Restarting Homebridge...
[6/30/2021, 12:30:56 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[6/30/2021, 12:30:56 PM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 3544
Initializing HAP-NodeJS v0.9.4...
[6/30/2021, 12:30:56 PM] Loaded config.json with 1 accessories and 1 platforms.
[6/30/2021, 12:30:56 PM] Loaded 0 cached accessories from cachedAccessories.
[6/30/2021, 12:30:56 PM] ---
[6/30/2021, 12:30:57 PM] Loaded plugin: homebridge-dummy@0.5.0
[6/30/2021, 12:30:57 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[6/30/2021, 12:30:57 PM] ---
[6/30/2021, 12:30:57 PM] Loaded plugin: homebridge-securitysystem@5.1.1
[6/30/2021, 12:30:57 PM] Registering accessory 'homebridge-securitysystem.security-system'
[6/30/2021, 12:30:57 PM] ---
[6/30/2021, 12:30:57 PM] Loaded plugin: homebridge-config-ui-x@4.41.1
[6/30/2021, 12:30:57 PM] Registering platform 'homebridge-config-ui-x.config'
[6/30/2021, 12:30:57 PM] ---
[6/30/2021, 12:30:57 PM] Loading 1 platforms...
[6/30/2021, 12:30:57 PM] [Config] Initializing config platform...
[6/30/2021, 12:30:57 PM] [Config] Running in Service Mode
[6/30/2021, 12:30:57 PM] Loading 1 accessories...
[6/30/2021, 12:30:57 PM] [Security System] Initializing security-system accessory...
[6/30/2021, 12:30:57 PM] [Security System] Default mode (Off)
[6/30/2021, 12:30:57 PM] [Security System] Arm delay (0 second/s)
[6/30/2021, 12:30:57 PM] [Security System] Trigger delay (0 second/s)
[6/30/2021, 12:30:57 PM] [Security System] Audio (Enabled)
Preparing Advertiser for 'Homebridge E48B A492' using bonjour-hap backend!
Setup Payload:
X-HM://0023ISYWYLJEL
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge E48B A492' using bonjour-hap backend!
[6/30/2021, 12:30:57 PM] Homebridge v1.3.4 (Homebridge E48B) is running on port 52347.

**Comment by MiguelRipoll23** [comment]
I see the issue clearly now.

First you must install ffmpeg, it's crashing because it can't start it to play audio.
Finally set `reset_minutes` to ten for example and then restart Homebridge to apply the new setting value.

**Comment by MiguelRipoll23** [comment]
If you install the latest release, it would inform you now if you don't have ffmpeg installed and the setting `Reset Delay Seconds` will block values smaller than 1.

Check when you can if that works for you.

**Comment by MiguelRipoll23** [comment]
Is the issue solved by the latest update?

**Comment by page-squared** [comment]
> Is the issue solved by the latest update?

Yes this is resolved. Thank you!
