### ISSUE TITLE
Update to 8.2.0, Home app stuck on "Arming..."

### ISSUE THREAD

**Issue by zbugrkx** [MiguelRipoll23/homebridge-securitysystem#565]
As the title says. I've had my system setup for a long time and running 8.1.2 with no issues.

As soon as I update to 8.2.0 or even 8.3 beta (to try if it helps) I am unable to arm the system from the Home app. 
It stays stuck to "arming..." and no automations run. From the plugin logs, it is detecting a change but that's is.

One small thing when running these newer versions, I notice that the button in home app does not react right away like its stuck to its current position and I need to tap twice to change state.

Downgraded back to 8.1.2 and all is working again.

Was there a big change that requires some configuration changes that I may have missed or unaware of?

Thanks,
Regards

**Comment by mwicki** [comment]
Hallo,
I have the same Problem. 

Here the homebridge log.


20.4.2024, 08:19:14] TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at SecuritySystem.updateArmingMotionDetected (/var/lib/homebridge/node_modules/homebridge-securitysystem/src/index.js:2429:34)
    at SecuritySystem.handleCurrentStateChange (/var/lib/homebridge/node_modules/homebridge-securitysystem/src/index.js:867:8)
    at SecuritySystem.setCurrentState (/var/lib/homebridge/node_modules/homebridge-securitysystem/src/index.js:809:8)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-securitysystem/src/index.js:1122:10)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
[20.4.2024, 08:19:14] Got SIGTERM, shutting down Homebridge...
[20.4.2024, 08:19:14] Got SIGTERM, shutting down child bridge process...
[20.4.2024, 08:19:14] Got SIGTERM, shutting down child bridge process...
[20.4.2024, 08:19:33] [Alarmanlage] Initializing security-system accessory...

**Comment by NogginTheNog** [comment]
Same issue here, had to reinstall the previous version.

**Comment by MiguelRipoll23** [comment]
Hi everyone,

Sorry about this. Issue happens when the new arming switch is disabled. I usually do testing with every option enabled and I missed this due to using a new way to add new accessories.

The 8.2.0 version will soon be removed to prevent it being downloaded and new patch update will fix the issue.

Sorry again, thanks for reporting the issue.

**Comment by MiguelRipoll23** [comment]
Reverting to 8.1.2 is recommended in the meantime.

A new beta update (8.3.0-beta.3) has been published for those who need or want to try the new arming sensor. Be aware that the 8.3.X betas introduce some internal changes that simplify mode changes, if you encounter any kind of issue that prevents the plugin from running smoothly please report it here.

**Comment by paul-a-lambert** [comment]
Hi Miguel, I'm on 9.1.0 and am seeing this issue. I recently changed the configuration to use a child bridge. Now when I try to change state, it gets stuck on Arming.
