### ISSUE TITLE
Plugin causes Homebridge to restart when changing security system state.

### ISSUE THREAD

**Issue by HumanSkunk** [MiguelRipoll23/homebridge-securitysystem#69]
A weird feature that started today is when I change alarm states my Homebridge instance crashes and restarts.

I get the error:

[10/5/2020, 19:02:43] [Home Alarm] ffplay -loglevel error -nodisp -i /usr/local/lib/node_modules/homebridge-securitysystem/src/../sounds/en-US/current-away.mp3 -autoexit -volume 50
[10/5/2020, 19:02:43] Error: spawn ffplay ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

I have configured it to only show 'Away' and 'Off'

I have the default sounds configured to play which worked fine until this morning. Took me a while to work out what was happening. I have a webhook set to tell me if Homebridge goes down and it only seemed to happen when the Security System changes state.

When homebridge restarts it is in its new state (i.e the one I selected) but all web hooks and commands linked with the status change don't run.

Disabling sounds and restarting causes the issue to go away. So I will do that for now.

I haven't seen this error prior to today. I have been running in debug mode as the recent updates with homebridge aren't playing nice with my setup.

**Comment by MiguelRipoll23** [comment]
Looks like you have to re-install ffmpeg using `sudo apt install ffmpeg`, not sure what happened 😦

**Comment by HumanSkunk** [comment]
How weird! I ran the install line again and its working.
